spring.application.name=audio
spring.ai.openai.api-key=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
spring.ai.openai.audio.transcription.base-url= https://api.openai.com
spring.ai.openai.audio.transcription.options.model = whisper-1
spring.ai.openai.audio.transcription.options.response-format = json



spring.datasource.url=jdbc:mysql://localhost:3306/audio_transcriber_db?useSSL=false&serverTimezone=UTC
spring.datasource.username = root
spring.datasource.password = admin@123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

spring.main.allow-bean-definition-overriding=true


erver.port=8080
